In [ ]:
"""
Code Challenge
  Name: 
    Automobile Analysis
  Filename: 
    automobile.py
  Problem Statement:
    (Automobile.csv)
    Read the Automobile.csv file and perform the following task :
    1. Handle the missing values for Price column
    2. Get the values from Price column into a numpy.ndarray
    3. Calculate the Minimum Price, Maximum Price, Average Price and Standard Deviation of Price
"""

In [13]:
import pandas as pd
import numpy as np

data= pd.read_csv("pd_csv/Automobile.csv")
data.head(15)

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.0
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.0
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,18920.0
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140.0,5500.0,17,20,23875.0
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
10,2,192.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16430.0
11,0,192.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800.0,23,29,16925.0
12,0,188.0,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,20970.0
13,0,188.0,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,21,28,21105.0
14,1,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,164,mpfi,3.31,3.19,9.0,121.0,4250.0,20,25,24565.0

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
symboling            205 non-null int64
normalized_losses    164 non-null float64
make                 205 non-null object
fuel_type            205 non-null object
aspiration           205 non-null object
num_doors            203 non-null object
body_style           205 non-null object
drive_wheels         205 non-null object
engine_location      205 non-null object
wheel_base           205 non-null float64
length               205 non-null float64
width                205 non-null float64
height               205 non-null float64
curb_weight          205 non-null int64
engine_type          205 non-null object
num_cylinders        205 non-null object
engine_size          205 non-null int64
fuel_system          205 non-null object
bore                 201 non-null float64
stroke               201 non-null float64
compression_ratio    205 non-null float64
horsepower           203 non-null float64
peak_rpm             203 non-null float64
city_mpg             205 non-null int64
highway_mpg          205 non-null int64
price                201 non-null float64
dtypes: float64(11), int64(5), object(10)
memory usage: 41.8+ KB

In [20]:
#1. Handle the missing values for Price column
dp= data[data['price'].isnull()].reset_index()    # give nan value records
dp

,index,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,NaN
1,44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,NaN
2,45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,...,90,2bbl,3.03,3.11,9.6,70.0,5400.0,38,43,NaN
3,129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,...,203,mpfi,3.94,3.11,10.0,288.0,5750.0,17,28,NaN

In [22]:
data['price']= data['price'].fillna(data['price'].mean())
data.head(10)

,symboling,normalized_losses,make,fuel_type,aspiration,num_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.000000
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.000000
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.000000
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.000000
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.000000
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,15250.000000
6,1,158.0,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,17710.000000
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110.0,5500.0,19,25,18920.000000
8,1,158.0,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140.0,5500.0,17,20,23875.000000
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500.0,16,22,13207.129353

In [27]:
#2. Get the values from Price column into a numpy.ndarray
price= np.array(data['price'])
print( price)

[13495.         16500.         16500.         13950.
 17450.         15250.         17710.         18920.
 23875.         13207.12935323 16430.         16925.
 20970.         21105.         24565.         30760.
 41315.         36880.          5151.          6295.
  6575.          5572.          6377.          7957.
  6229.          6692.          7609.          8558.
  8921.         12964.          6479.          6855.
  5399.          6529.          7129.          7295.
  7295.          7895.          9095.          8845.
 10295.         12945.         10345.          6785.
 13207.12935323 13207.12935323 11048.         32250.
 35550.         36000.          5195.          6095.
  6795.          6695.          7395.         10945.
 11845.         13645.         15645.          8845.
  8495.         10595.         10245.         10795.
 11245.         18280.         18344.         25552.
 28248.         28176.         31600.         34184.
 35056.         40960.         45400.         16503.
  5389.          6189.          6669.          7689.
  9959.          8499.         12629.         14869.
 14489.          6989.          8189.          9279.
  9279.          5499.          7099.          6649.
  6849.          7349.          7299.          7799.
  7499.          7999.          8249.          8949.
  9549.         13499.         14399.         13499.
 17199.         19699.         18399.         11900.
 13200.         12440.         13860.         15580.
 16900.         16695.         17075.         16630.
 17950.         18150.          5572.          7957.
  6229.          6692.          7609.          8921.
 12764.         22018.         32528.         34028.
 37028.         13207.12935323  9295.          9895.
 11850.         12170.         15040.         15510.
 18150.         18620.          5118.          7053.
  7603.          7126.          7775.          9960.
  9233.         11259.          7463.         10198.
  8013.         11694.          5348.          6338.
  6488.          6918.          7898.          8778.
  6938.          7198.          7898.          7788.
  7738.          8358.          9258.          8058.
  8238.          9298.          9538.          8449.
  9639.          9989.         11199.         11549.
 17669.          8948.         10698.          9988.
 10898.         11248.         16558.         15998.
 15690.         15750.          7775.          7975.
  7995.          8195.          8495.          9495.
  9995.         11595.          9980.         13295.
 13845.         12290.         12940.         13415.
 15985.         16515.         18420.         18950.
 16845.         19045.         21485.         22470.
 22625.        ]

In [29]:
# 3. Calculate the Minimum Price, Maximum Price, Average Price and Standard Deviation of Price
data['price'].describe()

count      205.000000
mean     13207.129353
std       7868.768212
min       5118.000000
25%       7788.000000
50%      10595.000000
75%      16500.000000
max      45400.000000
Name: price, dtype: float64